
loadTimeData.data = {
    "B": "B",
    "GB": "GB",
    "KB": "KB",
    "MB": "MB",
    "ad": "Reklam",
    "addSiteMenuLabel": "Lägg till webbplats",
    "addTopSiteDialogCancelButtonLabel": "Avbryt",
    "addTopSiteDialogNameInputPlaceHolder": "Webbplatsens titel",
    "addTopSiteDialogNameLabel": "Namn",
    "addTopSiteDialogSaveButtonLabel": "Spara",
    "addTopSiteDialogTitle": "Lägg till webbplats",
    "addTopSiteDialogURLInputPlaceHolder": "Webbadress",
    "addTopSiteDialogURLLabel": "Webbadress",
    "addWidget": "Lägg till",
    "adsTrackersBlocked": "Spårare och annonser blockerade",
    "backgroundColor": "#303443ff",
    "backgroundImageTitle": "Bakgrundsbild",
    "bookmarksPageTitle": "Visa och hantera bokmärken",
    "boxDdgButton": "Sök med DuckDuckGo",
    "boxTorButton": "Läs mer om Tor i Brave",
    "boxTorLabel": "Gör Privata fönster mer privata",
    "boxTorLabel2": "Detta Privata fönster är mer privat",
    "boxTorText": "Tor döljer din IP-adress från de webbplatser du besöker genom att dirigera din surfning genom flera Tor-servrar innan den når din destination. Tor kan göra surfningen långsammare och vissa webbplatser kanske inte fungerar alls.",
    "boxTorText2": "Användning av inkognitofönster ändrar bara vad Brave gör på din enhet — det ändrar inte någon annans beteende. Tor döljer din IP-adress från de webbplatser du besöker och gör det något svårare, men inte omöjligt, för din internetleverantör eller arbetsgivare att se vilka webbplatser du besöker. Öppna ett privat fönster med Tor från menyn eller med [[ key ]].",
    "boxTorTitle": "med Tor-anslutning",
    "brandedWallpaperOptIn": "Visa sponsrade bilder",
    "braveBackgroundImageOptionTitle": "Brave-bakgrunder",
    "braveBackgroundsTitle": "Brave-bakgrunder",
    "braveNewsActionRefresh": "Ladda nytt innehåll",
    "braveNewsAllSourcesHeader": "Källor",
    "braveNewsBackButton": "Bakåt",
    "braveNewsBackToDashboard": "Tillbaka till  $1Översikten$2",
    "braveNewsCategoryNameAll": "Alla källor",
    "braveNewsChannel-Brave": "Brave",
    "braveNewsChannel-Business": "Affärsliv",
    "braveNewsChannel-Cars": "Bilar",
    "braveNewsChannel-Crypto": "Krypto",
    "braveNewsChannel-Culture": "Kultur",
    "braveNewsChannel-Entertainment": "Underhållning",
    "braveNewsChannel-Entertainment News": "Nyheter om nöje",
    "braveNewsChannel-Fashion": "Mode",
    "braveNewsChannel-Film and TV": "Film och tv",
    "braveNewsChannel-Food": "Mat",
    "braveNewsChannel-Fun": "Nöje",
    "braveNewsChannel-Gaming": "Spel",
    "braveNewsChannel-Health": "Hälsa",
    "braveNewsChannel-Home": "Startsida",
    "braveNewsChannel-Music": "Musik",
    "braveNewsChannel-Politics": "Politik",
    "braveNewsChannel-Regional News": "Regionala nyheter",
    "braveNewsChannel-Science": "Vetenskap",
    "braveNewsChannel-Sports": "Sport",
    "braveNewsChannel-Tech News": "Nyheter om teknik",
    "braveNewsChannel-Tech Reviews": "Recensioner av teknik",
    "braveNewsChannel-Technology": "Teknik",
    "braveNewsChannel-Top News": "Toppnyheter",
    "braveNewsChannel-Top Sources": "Toppkällor",
    "braveNewsChannel-Travel": "Resor",
    "braveNewsChannel-US News": "USA nyheter",
    "braveNewsChannel-Weather": "Väder",
    "braveNewsChannel-World News": "Världsnyheter",
    "braveNewsChannelsHeader": "Kanaler",
    "braveNewsDirectSearchButton": "Få flöden från $1",
    "braveNewsDirectSearchNoResults": "Inga flöden hittades på $1",
    "braveNewsDisableSourceCommand": "Inaktivera innehåll från $1",
    "braveNewsErrorActionLabel": "Försök igen",
    "braveNewsErrorHeading": "Hoppsan …",
    "braveNewsErrorMessage": "Brave News kunde inte hämta innehåll.",
    "braveNewsFeedsHeading": "Följer",
    "braveNewsFollowButtonFollowing": "Sluta följa",
    "braveNewsFollowButtonNotFollowing": "Följ",
    "braveNewsIntroDescription": "Följ dina favoritkällor i ett enda flöde. Öppna bara en flik i Brave, bläddra ner och … voila!",
    "braveNewsIntroDescriptionTwo": "Brave News stöds av annonser med helt privata och anonymiserade annonser. $1Läs mer.$2.",
    "braveNewsIntroTitle": "Aktivera Brave News så missar du inga nyheter",
    "braveNewsNoContentActionLabel": "Välj innehållskällor",
    "braveNewsNoContentHeading": "Inget innehåll",
    "braveNewsNoContentMessage": "Brave News har inget innehåll att visa.",
    "braveNewsOptInActionLabel": "Aktivera Brave News",
    "braveNewsOptOutActionLabel": "Nej tack",
    "braveNewsPopularTitle": "Populära",
    "braveNewsResetAction": "Återställ Brave News-källor",
    "braveNewsResetConfirm": "Återställ alla dina Brave News-utgivarval till standard?",
    "braveNewsScrollHint": "Bläddra för Brave News",
    "braveNewsSearchPlaceholderLabel": "Sök efter webbplats, ämne eller RSS-feed",
    "braveNewsSearchQueryTooShort": "Fortsätt skriva för att söka efter källor",
    "braveNewsSearchResultsDirectResults": "Direktresultat",
    "braveNewsSearchResultsLocalResults": "Resultat",
    "braveNewsSearchResultsNoResults": "Det finns inget här :'(",
    "braveNewsSourcesTitle": "Källor",
    "braveNewsStatusFetching": "Hämtar",
    "braveNewsSuggestionsSubtitle": "Några källor du kanske gillar. Förslagen är anonyma och matchas bara på din enhet.",
    "braveNewsSuggestionsTitle": "Föslag",
    "braveNewsTitle": "Brave News",
    "braveNewsViewAllButton": "Visa alla",
    "braveRewardsTitle": "Brave Rewards",
    "braveTalkPromptAction": "Prova den",
    "braveTalkPromptAllowed": true,
    "braveTalkPromptDescription": "Starta obegränsade samtal med vänner och kollegor i Brave Talk.",
    "braveTalkPromptTitle": "Du kan starta ett privat samtal i Brave.",
    "braveTalkWidgetAboutData": "Om dina data",
    "braveTalkWidgetStartButton": "Starta samtal",
    "braveTalkWidgetTitle": "Brave Talk",
    "braveTalkWidgetWelcomeTitle": "Påbörja ett privat videosamtal med dina vänner och kollegor.",
    "cards": "Kort",
    "cardsToggleDesc": "Genom att stänga av kort, döljs alla kort som för närvarande syns. Du kan dock fortfarande meddelas om nya kort.",
    "cardsToggleTitle": "Kort",
    "clockFormat": "Format",
    "clockFormat12": "12-timmars klocka",
    "clockFormat24": "24-timmars klocka",
    "clockFormatDefault": "Automatisk",
    "clockTitle": "klocka",
    "close": "Stäng",
    "customBackgroundImageOptionTitle": "Använd din egen",
    "customBackgroundImageOptionUploadLabel": "Ladda upp från enhet",
    "customize": "Anpassa",
    "dashboardSettingsTitle": "Anpassa översikten",
    "day": "dag",
    "days": "dagar",
    "done": "Klart",
    "editCardsTitle": "Redigera kort",
    "editSiteTileMenuItem": "Redigera webbplats",
    "editTopSiteDialogTitle": "Redigera webbplats",
    "estimatedBandwidthSaved": "Bandbredd sparad",
    "estimatedTimeSaved": "Tid sparad",
    "featureCustomBackgroundEnabled": true,
    "featureFlagBraveNTPSponsoredImagesWallpaper": true,
    "featureFlagBraveNewsEnabled": true,
    "featureFlagBraveNewsPromptEnabled": true,
    "featureFlagBraveNewsV2Enabled": true,
    "fontfamily": "'Segoe UI', Tahoma, sans-serif",
    "fontfamilyMd": "Roboto, 'Segoe UI', Tahoma, sans-serif",
    "fontsize": "75%",
    "gradientColorTitle": "Toningar",
    "headerButton": "Lär dig mer.",
    "headerLabel": "Detta är ett",
    "headerText": "Brave minns inte vad du gör i ett privat fönster. Webbplatser som du besöker syns inte i din historik och kakor försvinner när du är klar. Privata fönster gör dig emellertid inte helt anonym online.",
    "headerText1": "Brave kommer aldrig ihåg vad du gör i ett privat fönster. Webbplatser du besöker visas inte i din historik. Cookies, formulärdata och webbplatsdata försvinner när du stänger fönstret.",
    "headerText2": "Uppmärksamma att din aktivitet fortfarande kan vara synlig för din internetleverantör, passiva nätverksobservatörer eller din arbetsgivare (om du använder en arbetsmaskin eller ett nätverk). För mer integritet, öppna ett privat fönster med Tor.",
    "headerTitle": "Privat fönster",
    "headerTorText": "Brave lagrar inte surfaktivitet från privata fönster. Med Tor-anslutning blir det svårare för webbplatser att se din riktiga IP-adress och för nätverksobservatörer att se vilka webbplatser du besöker. Men om din personliga säkerhet är beroende av att du är anonym bör du använda Tor Browser istället.",
    "headerTorTitle": "Privat fönster med Tor-anslutning",
    "hide": "Dölj",
    "hideWidget": "Dölj",
    "historyPageTitle": "Visa webbhistorik",
    "hour": "timme",
    "hours": "timmar",
    "httpsUpgraded": "HTTPS-uppgraderingar",
    "language": "sv",
    "learnMore": "Läs mer",
    "loading": "Läser in…",
    "minute": "minut",
    "minutes": "minuter",
    "photoBy": "Foto av",
    "preferencesPageTitle": "Ändra inställningar",
    "promoted": "Marknadsförd",
    "refreshBackgroundOnNewTab": "Uppdatera på varje ny flik",
    "removeTileMenuItem": "Ta bort",
    "restoreAll": "Återställ alla",
    "rewardsAboutRewards": "Med Belöningar i Brave kan du stötta kreatörer samtidigt som du tjänar BAT.",
    "rewardsAdGrantAmount": "$1 Rewards: $2",
    "rewardsAdGrantTitle": "Dina $1 Ad Rewards är här!",
    "rewardsBraveRewards": "Brave Rewards",
    "rewardsBrowserCannotReceiveAds": "Hoppsan! Din webbläsare kan inte ta emot privata annonser från Brave.",
    "rewardsBrowserNeedsUpdateToSeeAds": "För att fortsätta visa annonser behöver din webbläsare uppdateras.",
    "rewardsClaimRewards": "Hämta Rewards",
    "rewardsClaimTokens": "Hämta tokens",
    "rewardsConnectAccount": "Anslut konto",
    "rewardsConnectAccountNoProviders": "För att tjäna BAT måste användare koppla ett depåkonto till Belöningar i Brave. Tyvärr finns det ingen depå tillgänglig i din region, så det går inte att tjäna pengar. För närvarande stöds kreatörer automatiskt om du aktiverar Brave Belöningar.",
    "rewardsConnectAccountText": "$1Är du redo att börja tjäna pengar?$2 Anslut eller skapa ett konto med någon av våra partner.",
    "rewardsContinue": "Fortsätt",
    "rewardsEarning": "Vinstmedel",
    "rewardsEarningInfoText": "Tokens du tjänar den här månaden börjar behandlas den $1.",
    "rewardsEnableBraveAds": "Aktivera Brave-annonser",
    "rewardsExchangeValueNote": "Detta kan variera beroende på marknadens volatilitet.",
    "rewardsGiving": "Ge",
    "rewardsGrantDaysRemaining": "Du har $1 kvar att göra anspråk",
    "rewardsLearnMore": "Läs mer",
    "rewardsLogInToSeeBalance": "$1Logga in på $2$3 för att se ditt saldo",
    "rewardsOptInHeader": "Tjäna tokens och ge tillbaka",
    "rewardsOptInTerms": "Genom att fortsätta godkänner du $1Användarvillkoren$2 och $3Sekretesspolicyn$4.",
    "rewardsOptInText": "Tjäna tokens genom att visa Brave privata annonser och stöd innehållsskapare automatiskt.",
    "rewardsPaymentCheckStatus": "Kontrollera status",
    "rewardsPaymentCompleted": "Grattis! Din $1 är här!",
    "rewardsPaymentPending": "Dina $1 $2 kommer om $3",
    "rewardsPaymentProcessing": "Dina $1 belöning för $2 är på väg. Håll utkik!",
    "rewardsProgress": "Förlopp",
    "rewardsSelectCountryHeader": "Välj land",
    "rewardsSelectCountryText": "Om du vill fortsätta använda Brave Rewards väljer du ditt land så att vi kan visa dig rätt alternativ och annonser för din region. $1Sekretesspolicy$2",
    "rewardsSettings": "Rewards-inställningar",
    "rewardsStartUsingRewards": "Börja använda Belöningar",
    "rewardsTokenBalance": "Tokensaldo",
    "rewardsTokenGrantTitle": "En tokentilldelning är tillgänglig!",
    "rewardsUnsupportedRegionNoticeHeader": "Brave Rewards är tyvärr inte tillgängligt",
    "rewardsUnsupportedRegionNoticeLearnMore": "$1Läs mer$2",
    "rewardsUnsupportedRegionNoticeSubheader": "Tyvärr ser det ut som om du befinner dig i en region där Brave Rewards inte är tillgängligt.",
    "rewardsUnsupportedRegionNoticeText1": "Oroa dig inte.",
    "rewardsUnsupportedRegionNoticeText2": "Du kan fortfarande surfa privat.",
    "rewardsVBATNoticeText1": "$1 kommer vi att upphöra med stödet för befintliga virtuella BAT-saldon. Anslut ett depåkonto före detta datum så att vi kan överföra ditt intjänade saldo till ditt depåkonto, annars kommer ditt saldo att gå förlorat.",
    "rewardsVBATNoticeText2": "$1 kommer vi att upphöra med stödet för befintliga virtuella BAT-saldon. Tyvärr finns det inga tillgängliga förvaltare i din region ($2) för att ta ut dina intäkter. Fram till dess kan du fortfarande ge bidrag till dina favoritkreatörer.",
    "rewardsVBATNoticeTitle1": "Åtgärd krävs: Anslut ett depåkonto annars kommer dina vBAT att gå förlorade",
    "rewardsVBATNoticeTitle2": "Du har fortfarande tid att ge bidrag med din vBAT till dina favoritkreatörer",
    "rewardsWidgetBraveRewards": "Brave Rewards",
    "rewardsWidgetDesc": "Tjäna token när du tittar på annonser som respekterar din integritet.",
    "searchPromotionNTPPopupBottom": "Prova Brave Search nu",
    "searchPromotionNTPPopupDesc": "Brave Search snedvrider eller censurerar inte resultat, och det spårar inte dig, dina frågor eller dina klick.",
    "searchPromotionNTPPopupTitle1": "Vill du ha ännu bättre sekretess?",
    "searchPromotionNTPPopupTitle2": "Dags att sluta använda Google.",
    "searchPromotionSearchBoxPlaceholderLabel": "Sök privat på webben",
    "second": "sekund",
    "seconds": "sekunder",
    "settingsNavigateBack": "Bakåt",
    "showBackgroundImage": "Visa bakgrundsbilder",
    "showBraveStats": "Visa Brave-statistik",
    "showClock": "Visa klockan",
    "showFavoritesDesc": "Toppsidor väljs av dig",
    "showFavoritesLabel": "Favoriter",
    "showFavoritesMenuLabel": "Visa favoriter",
    "showFrecencyDesc": "Toppsidor föreslås baserat på webbplatser som du besöker ofta",
    "showFrecencyLabel": "Ofta besökta",
    "showFrecencyMenuLabel": "Visa ofta besökta",
    "showRewards": "Visa Brave Rewards",
    "showTopSites": "Toppsajter",
    "solidColorTitle": "Enfärgade färger",
    "sponsoredImageEarningTitle": "Du tjänar BAT för sponsrade bilder.",
    "sponsoredImageEnableRewards": "Aktivera belöningar",
    "sponsoredImageNotEarningTitle": "Du kan tjäna genom att titta på sponsrade bilder.",
    "sponsoredImageOffRewardsOnDescription": "Som Brave Rewards-användare kan du tjäna BAT när du tittar på sponsrade bilder.",
    "sponsoredImageOnAdsOff": "Du kan tjäna BAT när du tittar på sponsrade bilder när du aktiverar Brave-annonser. När Brave-annonser är inaktiverade så stöttar du fortfarande Brave när du aktiverar sponsrade bilder.",
    "sponsoredImageOnDescription": "Som en Brave Rewards-användare tjänar du BAT för sponsrade bilder du tittar på. Om du inaktiverar sponsrade bilder tjänar du mindre.",
    "sponsoredImageOnRewardsOnNoCustodianDescription": "Efter att du anslutit ett depåkonto till Brave Rewards kan du tjäna BAT när du tittar på sponsrade bilder. Fram till dess hjälper du till att stödja kreatörer när du tittar på sponsrade bilder.",
    "sponsoredImageRewardsOffDescription": "Du kan tjäna BAT när du tittar på sponsrade bilder med Brave Rewards. Är du inte Rewards-användare ännu? Om du aktiverar sponsrade bilder stöttar du fortfarande Braves uppdrag.",
    "statsTitle": "Brave-statistik",
    "textdirection": "ltr",
    "thumbRemoved": "Länken borttagen.",
    "topSitesTitle": "toppsajter",
    "undoRemoved": "Ångra"
};
